spring:
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/api/v1
        - CircuitBreaker=myCircuitBreaker

      routes:
        # Shopping-cart
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**

        # Shopping-store
        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**

        # Warehouse
        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/