grpc:
  server:
    port: 59090
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


hub-router:
  execution:
    mode: ANALYZE
    immediate-logging:
      enabled: true
    output:
      info-enabled: true
      trace-enabled: true
      print: true
      file: false