grpc:
  client:
    echo:
      address: 'static://localhost:9090'
      enable-keep-alive: true  # kebab-case предпочтительнее в YAML
      keep-alive-without-calls: true
      negotiation-type: plaintext