spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plus-smart-home-tech
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  
  sql:
    init:
      mode: always

analyzer:
  kafka:
    common-properties:
      bootstrap.servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumers:
      - type: SnapshotProcessor
        topics:
          - telemetry.snapshots.v1
        poll-timeout: PT5S
        properties:
          enable.auto.commit: false
          auto.offset.reset: earliest
          group.id: snapshot.group.id
          client.id: SnapshotProcessor
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotAvroDeserializer
      - type: HubEventProcessor
        topics:
          - telemetry.hubs.v1
        poll-timeout: PT5S
        properties:
          enable.auto.commit: false
          auto.offset.reset: earliest
          group.id: hubEvent.group.id
          client.id: HubEventProcessor
          value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventAvroDeserializer

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8083