spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

grpc:
  server:
    port: 59090
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    common-properties:
      bootstrap.servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable.auto.commit: false
    consumers:
      - type: SnapshotProcessor
        properties:
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
          group.id: telemetry.analyzer.snapshot
        topics:
          - telemetry.snapshots.v1
        poll-timeout: 500ms
      - type: HubEventProcessor
        properties:
          value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
          group.id: telemetry.analyzer.hub
        topics:
          - telemetry.hubs.v1
        poll-timeout: 100ms

hub-router:
  execution:
    mode: ANALYZE
    immediate-logging:
      enabled: true
    output:
      info-enabled: true
      trace-enabled: true
      print: true
      file: false