analyzer:
  kafka:
    common-properties:
      bootstrap.servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumers:
      - type: SnapshotProcessor
        topics:
          - telemetry.snapshots.v1
        poll-timeout: PT5S
        properties:
          enable.auto.commit: false
          auto.offset.reset: earliest
          group.id: snapshot.group.id
          client.id: SnapshotProcessor
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
      - type: HubEventProcessor  # <-- ???? ???? ????? ?????
        topics:
          - telemetry.hubs.v1
        poll-timeout: PT5S
        properties:
          enable.auto.commit: false
          auto.offset.reset: earliest
          group.id: hubEvent.group.id
          client.id: HubEventProcessor
          value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer